from tools.DOCUMENT_TOOLS import DOCUMENT_TOOLS
from tools.READ_TOOLS import READ_TOOLS
from tools.TICKET_PLAN_AND_CREATE import PLAN_AND_CREATE_TOOLS
from tools.WRITE_TOOLS import WRITE_TOOLS
from tools.TICKET_SIMILARITY import SIMILARITY_TOOLS

TOOLS = {}

TOOLS.update(READ_TOOLS)
TOOLS.update(PLAN_AND_CREATE_TOOLS)
TOOLS.update(WRITE_TOOLS)
TOOLS.update(SIMILARITY_TOOLS)
TOOLS.update(DOCUMENT_TOOLS)