from tools.READ_TOOLS import READ_TOOLS
from tools.TICKET_PLAN_AND_CREATE import PLAN_AND_CREATE_TOOLS
from tools.WRITE_TOOLS import WRITE_TOOLS

TOOLS = {}

TOOLS.update(READ_TOOLS)
TOOLS.update(PLAN_AND_CREATE_TOOLS)
TOOLS.update(WRITE_TOOLS)